sudo: false
language: node_js
node_js:
- iojs
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: stephen.austin@rovisys.com
  on:
    tags: true
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/4069f96dc5d0a074d13b
    on_success: change
    on_failure: always
    on_start: never
env:
  global:
    secure: QHH+LHNkYXG53I7L12RkKgFrlvYHsSc3H/jsRhuPqyUu+E15pFRfmuQWoEpnzhIkkg/MmPCSFJYs+qgIE7tgSH9mPyV3NRv594XpeADE+kkSY4kMNW02ZX7lcCtbJuMwxXsiWBUTw1WFf6cSKF+4dzl89kmZRv+JkAKeBoTdctagEwCet2VGP7xkzbnYxpDqnrmFROPF+JFQf0D6SaPTobbvyRYVIxTM1YxH2iNn9RYJCoj3ccxhW3ciaB79mPM0AasUe7njNp1BDlO4KBEQvPAHOPTm/6LbtmOfMcaxBLAmpjwQ4uTN+3rdmlwtnuR2+cnwTxEl9Wos39OyFw87pQ1LxHqmwctH18XhbcdZzuk7D+g3HQqKO2AmiGskjVrS0GC9EHWTb4ulNYaEFn1e/Q7AnaTE/ffzwWAE9mlePNAkgHWUf2CfDYLSlqGTJqgljQWVfQy1O4/8++OeliEIrmt3SEh5Sg8njuFe5gEC1e50bKbLHUxt9guDNRLSKGMSQNfrawqXXXHYByjeadhCLEkQxWzWvjXps9lxIlH9H2Dx2syZCKpV/cmEfhuSmtjxxUsF32qs8GbsWJALiRhKYIr78qPBmNpSdQQw7qZo0lko066hF3jmcfV8ETIJEM3uUEKeAaC5Ab+TV3+TTPaZubsQiThD8DM4IzvVv+73GV0=
